site_name: Translatium Documentation
repo_url: https://github.com/CEOXeon/Translatium
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Installation: 
    - Installation: usage/install.md
  - Endpoints: 
    - Examples: usage/examples.md
    - Automatic Generated Reference: usage/Automatic_Reference.md
  - Development: 
    -  Developer Guide: developer/developer.md

copyright: >
  Copyright &copy; 2024 - 2025 Louis Zimmermann

markdown_extensions:
  - toc
  - tables

plugins:
  - search
  - mkdocstrings

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
      - yaml
      - python
  features:
    - search.suggest
