site_name: Translatium Documentation
nav:
  - Home: index.md
  - Installation: usage/install.md
  - Endpoints: usage/endpoints.md
  - Development: developer/developer.md
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
      - yaml
      - python
